---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderms-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderms
  template:
    metadata:
      labels:
        app: orderms
    spec:
      containers:
      - name: orderms
        image: quay.io/ibmcase/eda-kc-order-cmd-mq:1.0-distroless
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: orderms-config