---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reeferms-config
data:
  FREEZER_REQUEST_QUEUE: DEV.FREEZER_REQUESTS
  FREEZER_RESPONSE_QUEUE: DEV.FREEZER_RESPONSES
  MQ_URL: "failover:(amqp://ibmmq:5672?jms.prefetchPolicy.queuePrefetch=1)"
  VOYAGE_REQUEST_QUEUE: DEV.VOYAGE_REQUEST
  VOYAGE_RESPONSE_QUEUE: DEV.VOYAGE_RESPONSE