---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reeferms-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reeferms
  template:
    metadata:
      labels:
        app: reeferms
    spec:
      containers:
      - name: reeferms
        image: quay.io/ibmcase/eda-kc-freezer-ms-mq
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: reeferms-config