apiVersion: v1
kind: ConfigMap
metadata:
  name: kc-reefer-ms-cm
data:
  APP_VERSION: 0.0.2
  MQ_URL: failover:(amqp://kc-mq-ibm-mq.kc-dev.svc?jms.prefetchPolicy.queuePrefetch=1)
  FREEZER_REQUEST_QUEUE: DEV.FREEZER_REQUESTS
  FREEZER_RESPONSE_QUEUE: DEV.FREEZER_RESPONSES