apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: kc-stage-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: kc-stage
    server: https://kubernetes.default.svc
  project: kc-mq
  source:
    path: environments/kc-stage/env/overlays
    repoURL: https://github.com/giovanni-savino/eda-kc-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
