---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-mq-ibm-mq
  annotations:
  namespace: kc-dev
  labels:
    app.kubernetes.io/instance: kc-mq-ibm-mq
    app.kubernetes.io/name: kc-mq-ibm-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kc-mq-ibm-mq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kc-mq-ibm-mq
    spec:
      containers:
      - name: kc-mq-ibm-mq
        image: quay.io/ibmcase/ibm-mqadvanced-server-dev:9.2.4.0-amd64
        ports:
        - containerPort: 1414
        - containerPort: 9443
        - containerPort: 5672
        envFrom:
        - configMapRef:
            name: kc-mq-config