apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: kc-mq
  namespace: kc-dev
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
    use: NonProduction
  queueManager:
    name: QM1
    metrics:
      enabled: true
    route:
      enabled: true
    storage:
      queueManager:
        type: ephemeral
    mqsc:
    - configMap:
        name: kc-mq-msqc
        items:
        - mqsc
  template:
    pod:
      containers:
      - name: qmgr
        image: quay.io/ibmcase/ibm-mqadvanced-server-dev:9.2.4.0-amd64
        env:
            - name: MQSNOAUT
              value: 'yes'

  version: 9.2.4.0-r1
  web:
    enabled: true

