---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyagems
  labels:
    name: voyagems
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voyagems
  template:
    metadata:
      labels:
        name: voyagems
    spec:
      containers:
      - name: voyagems
        image: quay.io/ibmcase/eda-kc-voyage-ms-mq:1.2-distroless
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: voyagems-config