---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyagems-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voyagems
  template:
    metadata:
      labels:
        app: voyagems
    spec:
      containers:
      - name: voyagems
        image: quay.io/ibmcase/eda-kc-voyage-ms-mq
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: voyagems-config